import SUBBG_Stayrak_1 from "@images/floor/stayrka_1.png";
import SUBBG_Foodmall_2 from "@images/floor/foodmall_2.png";



export const rightFloor = [
  {
    idx : 1,
    name : "연회장",
    localeName : "common.floor.stayrak_11f",
    floorName : "11~12F",
    bgImage :  SUBBG_Stayrak_1,
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층",
    mobileUrl : "https://m.place.naver.com/restaurant/1015897903/home?entry=pll",
    desktopUrl : "/banquet"
  },
  {
    idx : 2,
    name : "객실",
    localeName : "common.floor.stayrak_4f",
    bgImage :  SUBBG_Stayrak_1,
    floorName : "4~10F",
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층",
    mobileUrl : "https://m.place.naver.com/accommodation/1676380563/home?entry=pll&businessCategory=hotel",
    desktopUrl : "/rooms"
  },
  {
    idx : 3,
    name : "뷔폐",
    localeName : "common.floor.stayrak_3f",
    bgImage :  SUBBG_Stayrak_1,
    floorName : "3F",
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층",
    mobileUrl : "https://m.place.naver.com/restaurant/1015897903/home?entry=pll",
    desktopUrl : "/buffet"
  },
  {
    idx : 4,
    name : "레스토랑",
    localeName : "common.floor.stayrak_2f",
    bgImage :  SUBBG_Stayrak_1,
    floorName : "2F",
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층",
    mobileUrl : "https://m.place.naver.com/restaurant/1015897903/home?entry=pll",
    desktopUrl : "/restaurant"
  },
]

export const leftFloor = [
  {
    idx : 1,
    name : "루프가든",
    localeName : "common.floor.foodmall_5f",
    bgImage :  SUBBG_Foodmall_2,
    floorName : "5F",
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층, 11~12층",
    mobileUrl : "https://m.place.naver.com/restaurant/1015897903/home?entry=pll",
    desktopUrl : "/roofgarden"
  },
  {
    idx : 2,
    name : "성원정",
    localeName : "common.floor.foodmall_3f",
    bgImage :  SUBBG_Foodmall_2,
    floorName : "3~4F",
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층, 11~12층",
    mobileUrl : "https://m.place.naver.com/restaurant/1015897903/home?entry=pll",
    desktopUrl : "/sungwonjung"
  },
  {
    idx : 3,
    name : "스시노",
    localeName : "common.floor.foodmall_2f",
    bgImage :  SUBBG_Foodmall_2,
    floorName : "2F",
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층, 11~12층",
    mobileUrl : "https://m.place.naver.com/restaurant/1778402781/home?entry=pll",
    desktopUrl : "/sushino"
  },
  {
    idx : 4,
    name : "아뜰리에",
    localeName : "common.floor.foodmall_1f",
    bgImage :  SUBBG_Foodmall_2,
    floorName : "1F",
    subTtile : '소·중규모 연회장',
    desc : "최대 120석 규모의 피로연.연말연시 송년회 각종모임.워크샵.세미나.돌잔치,회갑등 목적에 따라 다양한 스타일의 행사가 가능합니다.",
    position : "성원푸드몰 3층, 11~12층",
    mobileUrl : "https://m.place.naver.com/restaurant/1428314034/home?entry=plt",
    desktopUrl : "/athliet"
  },
]


export const sungwonjungThumb = [
  {
    idx : 1,
    name : '건강한 밥상',
    localeName : "common.detail.sungwonjung_1",
  },
  {
    idx : 2,
    name : '14일간의 숙성',
    localeName : "common.detail.sungwonjung_2"
  },
  {
    idx : 3,
    name : '매일 새롭게',
    localeName : "common.detail.sungwonjung_3",
  },
  {
    idx : 4,
    name : '겨울철 보양식',
    localeName : "common.detail.sungwonjung_4"
  },
  {
    idx : 5,
    name : '부경한우 신메뉴 출시',
    localeName : "common.detail.sungwonjung_5"
  }
]

export const nationPhoneCode = [
  {label:'대한민국(+82)',code:'82',countryCode:'KR'},
  {label:'United States(+1)',code:'1',countryCode:'US'},
  {label:'日本(+81)',code:'81',countryCode:'JP'},
  {label:'中国(+86)',code:'86',countryCode:'CN'},
  {label:'Afghanistan(+93)',code:'93',countryCode:'AF'},
  {label:'Albania(+355)',code:'355',countryCode:'AL'},
  {label:'Algeria(+213)',code:'213',countryCode:'DZ'},
  {label:'American Samoa(+1 684)',code:'1 684',countryCode:'AS'},
  {label:'Andorra(+376)',code:'376',countryCode:'AD'},
  {label:'Angola(+244)',code:'244',countryCode:'AO'},
  {label:'Anguilla(+1 264)',code:'1 264',countryCode:'AI'},
  {label:'Antarctica(+64)',code:'64',countryCode:'AQ'},
  {label:'Antarctica(+672)',code:'672',countryCode:'AQ'},
  {label:'Antigua and Barbuda(+1 268)',code:'1 268',countryCode:'AG'},
  {label:'Argentina(+54)',code:'54',countryCode:'AR'},
  {label:'Armenia(+374)',code:'374',countryCode:'AM'},
  {label:'Aruba(+297)',code:'297',countryCode:'AW'},
  {label:'Ascension Island(+247)',code:'247',countryCode:'AC'},
  {label:'Australia(+61)',code:'61',countryCode:'AU'},
  {label:'Austria(+43)',code:'43',countryCode:'AT'},
  {label:'Azerbaijan(+994)',code:'994',countryCode:'AZ'},
  {label:'Bahamas(+1 242)',code:'1 242',countryCode:'BS'},
  {label:'Bahrain(+973)',code:'973',countryCode:'BH'},
  {label:'Bangladesh(+880)',code:'880',countryCode:'BD'},
  {label:'Barbados(+1 246)',code:'1 246',countryCode:'BB'},
  {label:'Belarus(+375)',code:'375',countryCode:'BY'},
  {label:'Belgium(+32)',code:'32',countryCode:'BE'},
  {label:'Belize(+501)',code:'501',countryCode:'BZ'},
  {label:'Benin(+229)',code:'229',countryCode:'BJ'},
  {label:'Bermuda(+1 441)',code:'1 441',countryCode:'BM'},
  {label:'Bhutan(+975)',code:'975',countryCode:'BT'},
  {label:'Bolivia(+591)',code:'591',countryCode:'BO'},
  {label:'Bosnia and Herzegovina(+387)',code:'387',countryCode:'BA'},
  {label:'Botswana(+267)',code:'267',countryCode:'BW'},
  {label:'Brazil(+55)',code:'55',countryCode:'BR'},
  {label:'British Virgin Islands(+1 284)',code:'1 284',countryCode:'VG'},
  {label:'Brunei(+673)',code:'673',countryCode:'BN'},
  {label:'Bulgaria(+359)',code:'359',countryCode:'BG'},
  {label:'Burkina Faso(+226)',code:'226',countryCode:'BF'},
  {label:'Burma (Myanmar)(+95)',code:'95',countryCode:'MM'},
  {label:'Burundi(+257)',code:'257',countryCode:'BI'},
  {label:'Cambodia(+855)',code:'855',countryCode:'KH'},
  {label:'Cameroon(+237)',code:'237',countryCode:'CM'},
  {label:'Canada(+1)',code:'1',countryCode:'CA'},
  {label:'Cape Verde(+238)',code:'238',countryCode:'CV'},
  {label:'Cayman Islands(+1 345)',code:'1 345',countryCode:'KY'},
  {label:'Central African Republic(+236)',code:'236',countryCode:'CF'},
  {label:'Chad(+235)',code:'235',countryCode:'TD'},
  {label:'Chile(+56)',code:'56',countryCode:'CL'},
  {label:'Christmas Island(+61)',code:'61',countryCode:'CX'},
  {label:'Cocos (Keeling) Islands(+61)',code:'61',countryCode:'CC'},
  {label:'Colombia(+57)',code:'57',countryCode:'CO'},
  {label:'Comoros(+269)',code:'269',countryCode:'KM'},
  {label:'Congo(+242)',code:'242',countryCode:'CG'},
  {label:'Cook Islands(+682)',code:'682',countryCode:'CK'},
  {label:'Costa Rica(+506)',code:'506',countryCode:'CR'},
  {label:'Croatia(+385)',code:'385',countryCode:'HR'},
  {label:'Cuba(+53)',code:'53',countryCode:'CU'},
  {label:'Cyprus(+357)',code:'357',countryCode:'CY'},
  {label:'Czech Republic(+420)',code:'420',countryCode:'CZ'},
  {label:'Democratic Republic of the Congo(+243)',code:'243',countryCode:'CD'},
  {label:'Denmark(+45)',code:'45',countryCode:'DK'},
  {label:'Diego Garcia(+246)',code:'246',countryCode:'DG'},
  {label:'Djibouti(+253)',code:'253',countryCode:'DJ'},
  {label:'Dominica(+1 767)',code:'1 767',countryCode:'DM'},
  {label:'Dominican Republic(+1 809)',code:'1 809',countryCode:'DO'},
  {label:'Dominican Republic(+1 829)',code:'1 829',countryCode:'DO'},
  {label:'Dominican Republic(+1 849)',code:'1 849',countryCode:'DO'},
  {label:'Ecuador(+593)',code:'593',countryCode:'EC'},
  {label:'Egypt(+20)',code:'20',countryCode:'EG'},
  {label:'El Salvador(+503)',code:'503',countryCode:'SV'},
  {label:'Equatorial Guinea(+240)',code:'240',countryCode:'GQ'},
  {label:'Eritrea(+291)',code:'291',countryCode:'ER'},
  {label:'Estonia(+372)',code:'372',countryCode:'EE'},
  {label:'Ethiopia(+251)',code:'251',countryCode:'ET'},
  {label:'Falkland Islands(+500)',code:'500',countryCode:'FK'},
  {label:'Faroe Islands(+298)',code:'298',countryCode:'FO'},
  {label:'Fiji(+679)',code:'679',countryCode:'FJ'},
  {label:'Finland(+358)',code:'358',countryCode:'FI'},
  {label:'France(+33)',code:'33',countryCode:'FR'},
  {label:'French Guiana(+594)',code:'594',countryCode:'GF'},
  {label:'French Polynesia(+689)',code:'689',countryCode:'PF'},
  {label:'Gabon(+241)',code:'241',countryCode:'GA'},
  {label:'Gambia(+220)',code:'220',countryCode:'GM'},
  {label:'Georgia(+995)',code:'995',countryCode:'GE'},
  {label:'Germany(+49)',code:'49',countryCode:'DE'},
  {label:'Ghana(+233)',code:'233',countryCode:'GH'},
  {label:'Gibraltar(+350)',code:'350',countryCode:'GI'},
  {label:'Greece(+30)',code:'30',countryCode:'GR'},
  {label:'Greenland(+299)',code:'299',countryCode:'GL'},
  {label:'Grenada(+1 473)',code:'1 473',countryCode:'GD'},
  {label:'Guadeloupe(+590)',code:'590',countryCode:'GP'},
  {label:'Guam(+1 671)',code:'1 671',countryCode:'GU'},
  {label:'Guatemala(+502)',code:'502',countryCode:'GT'},
  {label:'Guinea(+224)',code:'224',countryCode:'GN'},
  {label:'Guinea-Bissau(+245)',code:'245',countryCode:'GW'},
  {label:'Guyana(+592)',code:'592',countryCode:'GY'},
  {label:'Haiti(+509)',code:'509',countryCode:'HT'},
  {label:'Holy See (Vatican City)(+39)',code:'39',countryCode:'VA'},
  {label:'Honduras(+504)',code:'504',countryCode:'HN'},
  {label:'Hong Kong(+852)',code:'852',countryCode:'HK'},
  {label:'Hungary(+36)',code:'36',countryCode:'HU'},
  {label:'Iceland(+354)',code:'354',countryCode:'IS'},
  {label:'India(+91)',code:'91',countryCode:'IN'},
  {label:'Indonesia(+62)',code:'62',countryCode:'ID'},
  {label:'Iran(+98)',code:'98',countryCode:'IR'},
  {label:'Iraq(+964)',code:'964',countryCode:'IQ'},
  {label:'Ireland(+353)',code:'353',countryCode:'IE'},
  {label:'Isle of Man(+44)',code:'44',countryCode:'IM'},
  {label:'Israel(+972)',code:'972',countryCode:'IL'},
  {label:'Italy(+39)',code:'39',countryCode:'IT'},
  {label:'Ivory Coast(+225)',code:'225',countryCode:'CI'},
  {label:'Jamaica(+1 876)',code:'1 876',countryCode:'JM'},
  {label:'Jersey(+44)',code:'44',countryCode:'JE'},
  {label:'Jordan(+962)',code:'962',countryCode:'JO'},
  {label:'Kazakhstan(+7)',code:'7',countryCode:'KZ'},
  {label:'Kenya(+254)',code:'254',countryCode:'KE'},
  {label:'Kiribati(+686)',code:'686',countryCode:'KI'},
  {label:'Kuwait(+965)',code:'965',countryCode:'KW'},
  {label:'Kyrgyzstan(+996)',code:'996',countryCode:'KG'},
  {label:'Laos(+856)',code:'856',countryCode:'LA'},
  {label:'Latvia(+371)',code:'371',countryCode:'LV'},
  {label:'Lebanon(+961)',code:'961',countryCode:'LB'},
  {label:'Lesotho(+266)',code:'266',countryCode:'LS'},
  {label:'Liberia(+231)',code:'231',countryCode:'LR'},
  {label:'Libya(+218)',code:'218',countryCode:'LY'},
  {label:'Liechtenstein(+423)',code:'423',countryCode:'LI'},
  {label:'Lithuania(+370)',code:'370',countryCode:'LT'},
  {label:'Luxembourg(+352)',code:'352',countryCode:'LU'},
  {label:'Macau(+853)',code:'853',countryCode:'MO'},
  {label:'Macedonia(+389)',code:'389',countryCode:'MK'},
  {label:'Madagascar(+261)',code:'261',countryCode:'MG'},
  {label:'Malawi(+265)',code:'265',countryCode:'MW'},
  {label:'Malaysia(+60)',code:'60',countryCode:'MY'},
  {label:'Maldives(+960)',code:'960',countryCode:'MV'},
  {label:'Mali(+223)',code:'223',countryCode:'ML'},
  {label:'Malta(+356)',code:'356',countryCode:'MT'},
  {label:'Marshall Islands(+692)',code:'692',countryCode:'MH'},
  {label:'Martinique(+596)',code:'596',countryCode:'MQ'},
  {label:'Mauritania(+222)',code:'222',countryCode:'MR'},
  {label:'Mauritius(+230)',code:'230',countryCode:'MU'},
  {label:'Mayotte(+262)',code:'262',countryCode:'YT'},
  {label:'Mexico(+52)',code:'52',countryCode:'MX'},
  {label:'Micronesia(+691)',code:'691',countryCode:'FM'},
  {label:'Moldova(+373)',code:'373',countryCode:'MD'},
  {label:'Monaco(+377)',code:'377',countryCode:'MC'},
  {label:'Mongolia(+976)',code:'976',countryCode:'MN'},
  {label:'Montenegro(+382)',code:'382',countryCode:'ME'},
  {label:'Montserrat(+1 664)',code:'1 664',countryCode:'MS'},
  {label:'Morocco(+212)',code:'212',countryCode:'MA'},
  {label:'Mozambique(+258)',code:'258',countryCode:'MZ'},
  {label:'Namibia(+264)',code:'264',countryCode:'NA'},
  {label:'Nauru(+674)',code:'674',countryCode:'NR'},
  {label:'Nepal(+977)',code:'977',countryCode:'NP'},
  {label:'Netherlands(+31)',code:'31',countryCode:'NL'},
  {label:'Netherlands Antilles(+599)',code:'599',countryCode:'AN'},
  {label:'New Caledonia(+687)',code:'687',countryCode:'NC'},
  {label:'New Zealand(+64)',code:'64',countryCode:'NZ'},
  {label:'Nicaragua(+505)',code:'505',countryCode:'NI'},
  {label:'Niger(+227)',code:'227',countryCode:'NE'},
  {label:'Nigeria(+234)',code:'234',countryCode:'NG'},
  {label:'Niue(+683)',code:'683',countryCode:'NU'},
  {label:'Norfolk Island(+672)',code:'672',countryCode:'NF'},
  {label:'North Korea(+850)',code:'850',countryCode:'KP'},
  {label:'Northern Mariana Islands(+1 670)',code:'1 670',countryCode:'MP'},
  {label:'Norway(+47)',code:'47',countryCode:'NO'},
  {label:'Oman(+968)',code:'968',countryCode:'OM'},
  {label:'Pakistan(+92)',code:'92',countryCode:'PK'},
  {label:'Palau(+680)',code:'680',countryCode:'PW'},
  {label:'Palestine(+970)',code:'970',countryCode:'PS'},
  {label:'Panama(+507)',code:'507',countryCode:'PA'},
  {label:'Papua New Guinea(+675)',code:'675',countryCode:'PG'},
  {label:'Paraguay(+595)',code:'595',countryCode:'PY'},
  {label:'Peru(+51)',code:'51',countryCode:'PE'},
  {label:'Philippines(+63)',code:'63',countryCode:'PH'},
  {label:'Pitcairn Islands(+870)',code:'870',countryCode:'PN'},
  {label:'Poland(+48)',code:'48',countryCode:'PL'},
  {label:'Portugal(+351)',code:'351',countryCode:'PT'},
  {label:'Puerto Rico(+1 939)',code:'1 939',countryCode:'PR'},
  {label:'Puerto Rico(+1 787)',code:'1 787',countryCode:'PR'},
  {label:'Qatar(+974)',code:'974',countryCode:'QA'},
  {label:'Republic of the Congo(+242)',code:'242',countryCode:'CG'},
  {label:'Reunion Island(+262)',code:'262',countryCode:'RE'},
  {label:'Romania(+40)',code:'40',countryCode:'RO'},
  {label:'Russia(+7)',code:'7',countryCode:'RU'},
  {label:'Rwanda(+250)',code:'250',countryCode:'RW'},
  {label:'Saint Barthelemy(+590)',code:'590',countryCode:'BL'},
  {label:'Saint Helena(+290)',code:'290',countryCode:'SH'},
  {label:'Saint Kitts and Nevis(+1 869)',code:'1 869',countryCode:'KN'},
  {label:'Saint Lucia(+1 758)',code:'1 758',countryCode:'LC'},
  {label:'Saint Martin(+590)',code:'590',countryCode:'MF'},
  {label:'Saint Pierre and Miquelon(+508)',code:'508',countryCode:'PM'},
  {label:'Saint Vincent and the Grenadines(+1 784)',code:'1 784',countryCode:'VC'},
  {label:'Samoa(+685)',code:'685',countryCode:'WS'},
  {label:'San Marino(+378)',code:'378',countryCode:'SM'},
  {label:'Sao Tome and Principe(+239)',code:'239',countryCode:'ST'},
  {label:'Saudi Arabia(+966)',code:'966',countryCode:'SA'},
  {label:'Senegal(+221)',code:'221',countryCode:'SN'},
  {label:'Serbia(+381)',code:'381',countryCode:'RS'},
  {label:'Seychelles(+248)',code:'248',countryCode:'SC'},
  {label:'Sierra Leone(+232)',code:'232',countryCode:'SL'},
  {label:'Singapore(+65)',code:'65',countryCode:'SG'},
  {label:'Sint Maarten(+1 721)',code:'1 721',countryCode:'SX'},
  {label:'Slovakia(+421)',code:'421',countryCode:'SK'},
  {label:'Slovenia(+386)',code:'386',countryCode:'SI'},
  {label:'Solomon Islands(+677)',code:'677',countryCode:'SB'},
  {label:'Somalia(+252)',code:'252',countryCode:'SO'},
  {label:'South Africa(+27)',code:'27',countryCode:'ZA'},
  {label:'South Sudan(+211)',code:'211',countryCode:'SS'},
  {label:'Spain(+34)',code:'34',countryCode:'ES'},
  {label:'Sri Lanka(+94)',code:'94',countryCode:'LK'},
  {label:'Sudan(+249)',code:'249',countryCode:'SD'},
  {label:'Suriname(+597)',code:'597',countryCode:'SR'},
  {label:'Svalbard(+47)',code:'47',countryCode:'SJ'},
  {label:'Swaziland(+268)',code:'268',countryCode:'SZ'},
  {label:'Sweden(+46)',code:'46',countryCode:'SE'},
  {label:'Switzerland(+41)',code:'41',countryCode:'CH'},
  {label:'Syria(+963)',code:'963',countryCode:'SY'},
  {label:'Taiwan(+886)',code:'886',countryCode:'TW'},
  {label:'Tajikistan(+992)',code:'992',countryCode:'TJ'},
  {label:'Tanzania(+255)',code:'255',countryCode:'TZ'},
  {label:'Thailand(+66)',code:'66',countryCode:'TH'},
  {label:'Timor-Leste (East Timor)(+670)',code:'670',countryCode:'TL'},
  {label:'Togo(+228)',code:'228',countryCode:'TG'},
  {label:'Tokelau(+690)',code:'690',countryCode:'TK'},
  {label:'Tonga Islands(+676)',code:'676',countryCode:'TO'},
  {label:'Trinidad and Tobago(+1 868)',code:'1 868',countryCode:'TT'},
  {label:'Tunisia(+216)',code:'216',countryCode:'TN'},
  {label:'Turkey(+90)',code:'90',countryCode:'TR'},
  {label:'Turkmenistan(+993)',code:'993',countryCode:'TM'},
  {label:'Turks and Caicos Islands(+1 649)',code:'1 649',countryCode:'TC'},
  {label:'Tuvalu(+688)',code:'688',countryCode:'TV'},
  {label:'Uganda(+256)',code:'256',countryCode:'UG'},
  {label:'Ukraine(+380)',code:'380',countryCode:'UA'},
  {label:'United Arab Emirates(+971)',code:'971',countryCode:'AE'},
  {label:'United Kingdom(+44)',code:'44',countryCode:'GB'},
  {label:'Uruguay(+598)',code:'598',countryCode:'UY'},
  {label:'US Virgin Islands(+1 340)',code:'1 340',countryCode:'VI'},
  {label:'Uzbekistan(+998)',code:'998',countryCode:'UZ'},
  {label:'Vanuatu(+678)',code:'678',countryCode:'VU'},
  {label:'Venezuela(+58)',code:'58',countryCode:'VE'},
  {label:'Vietnam(+84)',code:'84',countryCode:'VN'},
  {label:'Wallis and Futuna(+681)',code:'681',countryCode:'WF'},
  {label:'Western Sahara(+212)',code:'212',countryCode:'EH'},
  {label:'Yemen(+967)',code:'967',countryCode:'YE'},
  {label:'Zambia(+260)',code:'260',countryCode:'ZM'},
  {label:'Zimbabwe(+263)',code:'263',countryCode:'ZW'}
]

const contrants  = {
  defaultColor : '#6c62d1',
  projectTitle : 'SW ERP',
  popDetailSizeRule1 : 1024,// 멀티뷰 최소너비 기준지점
  popDetailSizeRule2 : '800px',//멀티뷰최소너비
  popDetailSizeRule3 : '80%',//  멀티뷰 최소너비 이상일때 너비 비율
  popDetailSizeRule4 : '700px',// 싱글뷰 기준 너비
  rightFixedWidth : '550px',
  highrightOrderCount : 100000, //주문조회리스트 하이라이트 기준주문금액
  sidebarWidth: 86,
  headerHeight: 56,
  mobileSidebarWidth: 0,
  mobileHeaderHeight: 60,
  desktopMinWidth : 1600,


  //실시간 상담 해피콜 
  happyCallUrl : "https://customer.happytalk.io/public_v1/chat_v4/public_point?go=C&is_login=N&uid=&cus_extra_username=&cus_extra_phone=&cus_extra_email=&phone_number=&parameter1=guest&parameter2=guest&site_id=4000001034&category_id=98115&division_id=98116&usergb=W&title=%5B%ED%85%8C%EC%8A%A4%ED%8A%B8+%EC%83%81%EB%8B%B4%EC%B0%BD%5D"
}

export default contrants;
